# mypy configuration for HX-Infrastructure
[tool.mypy]
python_version = "3.12"

# Type checking strictness
warn_return_any = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

# Error handling
strict_optional = true
no_implicit_optional = true
show_error_codes = true
show_column_numbers = true

# Import handling
ignore_missing_imports = true
follow_imports = "normal"

# Per-module options
[[tool.mypy.overrides]]
module = [
    "litellm",
    "langfuse",
    "respx",
    "tests.*"
]
ignore_errors = true

[[tool.mypy.overrides]]
module = "gateway.src.*"
disallow_untyped_defs = true
disallow_incomplete_defs = true
