general_settings:
  master_key: ${MASTER_KEY:?MASTER_KEY environment variable must be set}
  background_health_checks: true
  health_check_interval: 300  # Check every 5 minutes
  health_check_timeout: 30    # 30 second timeout for health probes
  health_check_max_retries: 3 # Retry failed checks 3 times before marking as unhealthy
  health_check_backoff: 10    # Wait 10 seconds between retries

model_list:
  # --- Embeddings (orc) ---
  - model_name: emb-premium
    litellm_params: { model: "ollama/mxbai-embed-large", api_base: "http://192.168.10.31:11434" }
  - model_name: emb-perf
    litellm_params: { model: "ollama/nomic-embed-text",  api_base: "http://192.168.10.31:11434" }
  - model_name: emb-light
    litellm_params: { model: "ollama/all-minilm",       api_base: "http://192.168.10.31:11434" }

  # --- LLM-01 Models (192.168.10.29) ---
  - model_name: llm01-llama3.2-3b
    litellm_params: { model: "ollama/llama3.2:3b", api_base: "http://192.168.10.29:11434" }
  - model_name: llm01-qwen3-1.7b
    litellm_params: { model: "ollama/qwen3:1.7b", api_base: "http://192.168.10.29:11434" }
  - model_name: llm01-mistral-small3.2
    litellm_params: { model: "ollama/mistral-small3.2:latest", api_base: "http://192.168.10.29:11434" }
