# /opt/HX-Infrastructure-/api-gateway/config/api-gateway/routing.yaml
routing:
  strategy: ml-based-routing
  default_group: hx-chat
  failover_order: ["llm02-phi3", "llm01-llama3.2-3b", "llm02-gemma2-2b"]
  # Weights are used if ML score ties or no features available
  static_weights:
    llm01-llama3.2-3b: 0.4
    llm02-phi3: 0.4
    llm02-gemma2-2b: 0.2
features:
  # Sources for dynamic features – stubs now, ready for Prometheus/Redis later
  load_source: "none"              # future: "prometheus"
  perf_source: "none"              # future: "prometheus"
  specialization_source: "registry"
timeouts:
  connect_s: 2
  read_s: 30
retries:
  total: 2
