#!/bin/bash
# CUDA Environment Verification Script
# Generated by Ansible for Citadel Alpha AI Processing Tier

echo "=== CUDA Environment Verification ==="
echo "CUDA Home: $CUDA_HOME"
echo "CUDA in PATH: $(which nvcc 2>/dev/null || echo 'Not found')"

echo ""
echo "=== NVCC Version ==="
nvcc --version 2>/dev/null || echo "NVCC not accessible"

echo ""
echo "=== GPU Status ==="
nvidia-smi -L

echo ""
echo "=== CUDA Libraries ==="
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
ls -la $CUDA_HOME/lib64/libcudart.so* 2>/dev/null || echo "CUDA runtime libraries not found"

echo ""
echo "=== Test GPU-CUDA Integration ==="
python3 -c "
try:
    import subprocess
    result = subprocess.run(['nvidia-smi', '--query-gpu=name,driver_version,cuda_version', '--format=csv,noheader'], 
                          capture_output=True, text=True)
    print('GPU-CUDA Status:', result.stdout.strip() if result.returncode == 0 else 'Failed')
except Exception as e:
    print('Python GPU test failed:', e)
"
